schema:
  - "# X £ £ £ $ $ X #"
items:
  - '£;SHUFFLING_REWARD'
  - '$;STATIC_REWARD'
  - '#;COUNTDOWN_SLOT'
  - 'X;BLACK_STAINED_GLASS_PANE'
settings:
  total_duration: 10
  shuffling_reward:
    interval: 5
  static_reward:
    type: "BONUS"